class AppText {
  static final Map<String, Map<String, String>> text = {
    "English": {
      "number": "Give your number",
      "title": "Enter your mobile number",
      "sendOtp": "Send OTP",
      "otpSent": "OTP Sent Successfully",
      "otpVerification": "OTP Verification",
      "yourOtp": "Your OTP is 875276",
      "enterOtp": "Enter OTP",
      "continue": "Continue",
      "whoAreYou": "Who are you?",
      "roleSubtitle": "Select your role",
      "farmer": "Farmer",
      "buyer": "Buyer",
      "farmerDesc": "I sell crops",
      "buyerDesc": "I buy products",

      // NEW
      "home": "Home",
      "orders": "Orders",
      "sell": "Sell",
      "alerts": "Alerts",
      "profile": "Profile",
      "verifiedSeller": "Verified Seller",
      "todayMandi": "Today's Mandi",
      "activeListings": "Active Listings",
      "noListing": "No listing yet",
      "addListing": "Add Listing",
      "cropName": "Crop Name",
      "quantity": "Quantity",
      "pricePerKg": "Price per kg",
      "photoGrade": "Photo & Grade",
      "qualityGrade": "Quality Grade",
      "deliveryOption": "Delivery Option",
      "publishListing": "Publish Listing",
      "saveDraft": "Save Draft",
      "noOrders": "No orders yet",
    },

    "Hindi": {
      "number": "अपना नंबर दें",
      "title": "अपना मोबाइल नंबर दर्ज करें",
      "sendOtp": "OTP भेजें",
      "otpSent": "OTP सफलतापूर्वक भेजा गया",
      "otpVerification": "OTP सत्यापन",
      "yourOtp": "आपका OTP है 875276",
      "enterOtp": "OTP दर्ज करें",
      "continue": "जारी रखें",
      "whoAreYou": "आप कौन हैं?",
      "roleSubtitle": "अपनी भूमिका चुनें",
      "farmer": "किसान",
      "buyer": "खरीदार",
      "farmerDesc": "मैं फसल बेचता हूँ",
      "buyerDesc": "मैं खरीदता हूँ",

      // NEW
      "home": "होम",
      "orders": "ऑर्डर",
      "sell": "बेचें",
      "alerts": "अलर्ट",
      "profile": "प्रोफाइल",
      "verifiedSeller": "सत्यापित विक्रेता",
      "todayMandi": "आज मंडी भाव",
      "activeListings": "सक्रिय लिस्टिंग",
      "noListing": "अभी कोई लिस्टिंग नहीं",
      "addListing": "फसल बेचें",
      "cropName": "फसल का नाम",
      "quantity": "मात्रा",
      "pricePerKg": "प्रति किलो मूल्य",
      "photoGrade": "फोटो और ग्रेड",
      "qualityGrade": "गुणवत्ता ग्रेड",
      "deliveryOption": "डिलीवरी विकल्प",
      "publishListing": "लिस्टिंग प्रकाशित करें",
      "saveDraft": "ड्राफ्ट सेव करें",
      "noOrders": "अभी कोई ऑर्डर नहीं",
    },

    "Bangla": {
      "number": "আপনার নম্বর দিন",
      "title": "আপনার মোবাইল নম্বর লিখুন",
      "sendOtp": "OTP পাঠান",
      "otpSent": "OTP সফলভাবে পাঠানো হয়েছে",
      "otpVerification": "OTP যাচাইকরণ",
      "yourOtp": "আপনার OTP হলো 875276",
      "enterOtp": "OTP লিখুন",
      "continue": "চালিয়ে যান",
      "whoAreYou": "আপনি কে?",
      "roleSubtitle": "আপনার ভূমিকা নির্বাচন করুন",
      "farmer": "কৃষক",
      "buyer": "ক্রেতা",
      "farmerDesc": "আমি ফসল বিক্রি করি",
      "buyerDesc": "আমি কিনি",

      // NEW
      "home": "হোম",
      "orders": "অর্ডার",
      "sell": "বিক্রি",
      "alerts": "সতর্কতা",
      "profile": "প্রোফাইল",
      "verifiedSeller": "যাচাইকৃত বিক্রেতা",
      "todayMandi": "আজকের বাজার",
      "activeListings": "সক্রিয় তালিকা",
      "noListing": "এখনও কোনো তালিকা নেই",
      "addListing": "পণ্য তালিকা",
      "cropName": "ফসলের নাম",
      "quantity": "পরিমাণ",
      "pricePerKg": "প্রতি কেজির দাম",
      "photoGrade": "ছবি ও গ্রেড",
      "qualityGrade": "মানের গ্রেড",
      "deliveryOption": "ডেলিভারি অপশন",
      "publishListing": "তালিকা প্রকাশ করুন",
      "saveDraft": "খসড়া সংরক্ষণ",
      "noOrders": "এখনও কোনো অর্ডার নেই",
    },
  };
}
